LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_http_module modules/mod_proxy_http.so
LoadModule headers_module modules/mod_headers.so

<Location "/">
	AuthType Basic
	AuthName "Archives de cours"
	AuthUserFile "/usr/local/apache2/conf/.htpasswd"
	Require valid-user
</Location>

<Directory "/usr/local/apache2/htdocs/notes">
	Options +Indexes
	IndexOptions FancyIndexing NameWidth=* HTMLTable Charset=UTF-8
</Directory>

ProxyPreserveHost On
ProxyPass "/editor/" "http://editor:80/editor/"
ProxyPassReverse "/editor/" "http://editor:80/editor/"
RequestHeader set X-Forwarded-Proto "http"
